(()=>{
const host=document.getElementById('seriesStudy');
let configs=[{name:'唯識真義',key:'weishi',tag:'唯識真義',terms:['阿賴耶識','種子','熏習','轉識成智'],image:'photo-1782099149263-52e8c2451882',credit:'Miruthula Adiyamane',source:'misty-forest-landscape-with-mountains-at-sunrise-PvPq9Uq0674',tint:'#edf4e8'},{name:'Seth 賽斯',key:'seth',tag:'Seth賽斯',terms:['信念','個人實相','意識','可能性'],image:'photo-1772974855212-eb5cb569c2b1',credit:'Asse Slotendijk',source:'sunlight-breaking-through-dramatic-dark-clouds-4I_2LAYfGeI',tint:'#edf1f8'},{name:'阿乙莎',key:'ayesha',tag:'阿乙莎',terms:['愛','內在連結','自我接納','創造'],image:'photo-1759240215290-ae7bf20113c1',credit:'James Lo',source:'misty-mountain-range-at-sunrise-with-soft-sky-e2jg_yxfBNA',tint:'#f8efe5'}];
let stored={};try{stored=JSON.parse(localStorage.getItem('shiyeSeriesStudy')||'{}')||{}}catch{}try{const saved=JSON.parse(localStorage.getItem('shiyeSeriesConfigs')||'null');if(Array.isArray(saved))configs=saved.filter(c=>c&&typeof c.name==='string'&&typeof c.key==='string'&&Array.isArray(c.terms))}catch{}for(const c of configs)c.terms=[...new Set([...c.terms,...Object.keys(stored[c.key]||{})])];let current=0,term=configs[0]?.terms[0]||'';
const management='<div class="study-manage"><button type="button" id="studyAddSeries">＋ 新增系列</button><button type="button" id="studyDeleteSeries">刪除目前系列</button></div><form id="studySeriesForm" hidden><label>系列名稱<input id="studySeriesName" required maxlength="60"></label><label>文章標籤（選填）<input id="studySeriesTag" placeholder="例如：Seth賽斯"></label><label>風景背景<select id="studySeriesBackground"><option value="0">霧林</option><option value="1">天空</option><option value="2">晨光山景</option></select></label><button type="submit">建立系列</button><button type="button" id="studyCancelSeries">取消</button></form>';
const backgroundPresets=[{image:'photo-1782099149263-52e8c2451882',credit:'Miruthula Adiyamane',source:'misty-forest-landscape-with-mountains-at-sunrise-PvPq9Uq0674',tint:'#edf4e8'},{image:'photo-1772974855212-eb5cb569c2b1',credit:'Asse Slotendijk',source:'sunlight-breaking-through-dramatic-dark-clouds-4I_2LAYfGeI',tint:'#edf1f8'},{image:'photo-1759240215290-ae7bf20113c1',credit:'James Lo',source:'misty-mountain-range-at-sunrise-with-soft-sky-e2jg_yxfBNA',tint:'#f8efe5'}];
function saveConfigs(){localStorage.setItem('shiyeSeriesConfigs',JSON.stringify(configs));persist()}
function bindManagement(){
const find=id=>host.querySelector('#'+id);find('studyAddSeries').onclick=()=>{find('studySeriesForm').hidden=false;find('studySeriesName').focus()};find('studyCancelSeries').onclick=()=>find('studySeriesForm').hidden=true;find('studyDeleteSeries').hidden=!configs.length;find('studyDeleteSeries').onclick=()=>{const config=configs[current];if(!confirm('刪除「'+config.name+'」系列及其中的名詞、整理與文章連結？'))return;delete stored[config.key];configs.splice(current,1);current=Math.max(0,Math.min(current,configs.length-1));term=configs[current]?.terms[0]||'';saveConfigs();render()};find('studySeriesForm').onsubmit=e=>{e.preventDefault();const name=find('studySeriesName').value.trim();if(!name)return;const existing=configs.findIndex(c=>c.name===name);if(existing>=0){current=existing;term=configs[current].terms[0]||'';render();return}configs.push({...backgroundPresets[Number(find('studySeriesBackground').value)],name,tag:find('studySeriesTag').value.trim(),key:'series-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8),terms:[]});current=configs.length-1;term='';saveConfigs();render()}}

function data(){const key=configs[current].key;if(!stored[key]||typeof stored[key]!=='object')stored[key]={};if(!stored[key][term])stored[key][term]={lead:'',own:'',example:'',question:'',links:[]};return stored[key][term]}
function persist(){localStorage.setItem('shiyeSeriesStudy',JSON.stringify(stored))}
const text=value=>esc(value||'');
function render(){if(!configs.length){host.innerHTML='<h2>系列深讀</h2>'+management+'<p class="empty">還沒有系列，新增一個開始整理。</p>';host.style.removeProperty('--study-photo');bindManagement();return}const config=configs[current],note=term?data():{lead:'',own:'',example:'',question:'',links:[]},terms=config.terms;host.style.setProperty('--study-tint',config.tint);host.style.setProperty('--study-photo',`url("https://images.unsplash.com/${config.image}?auto=format&fit=crop&w=1800&q=85")`);host.innerHTML=`<div class="section-head"><div><h2>系列深讀</h2><p class="section-desc">從重要名詞出發，把文章與自己的理解連起來。</p></div></div>${management}<div class="study-tabs">${configs.map((c,i)=>`<button type="button" data-series="${i}" aria-pressed="${i===current}">${text(c.name)}</button>`).join('')}</div><div class="study-heading"><h3>${text(config.name)}</h3><div><button type="button" id="studyAddTerm">＋ 新增名詞</button> <button type="button" id="studyDeleteTerm">刪除目前名詞</button></div></div><form id="studyTermForm" hidden><label>名詞<input id="studyTermName" required maxlength="60"></label><button type="submit">新增</button><button type="button" id="studyCancelTerm">取消</button></form><div class="study-tabs">${terms.map(t=>`<button type="button" data-term="${text(t)}" aria-pressed="${t===term}">${text(t)}</button>`).join('')}</div><div class="study-intro"><small>閱讀的入口</small><h3>${text(term)}</h3><p>${text(note.lead)||'這個名詞對我有什麼意義？哪些文章可以幫助我理解它？'}</p></div><div class="study-columns"><section class="study-panel"><div class="study-heading"><h3>從文章看這個名詞</h3><button type="button" id="studyAddArticle">＋ 連結文章</button></div><form id="studySearchForm" hidden><label>搜尋文章<input id="studySearch" type="search" placeholder="搜尋標題、作者或標籤"></label><div id="studySearchResults"></div><button type="button" id="studyCancelSearch">取消</button></form><div id="studyArticles"></div></section><section class="study-panel"><div class="study-heading"><h3>我的理解與整理</h3><button type="button" id="studyEdit">✎ 編輯</button></div><div id="studyRead">${[['own','用自己的話說'],['example','生活中的例子'],['question','還没想清楚的問題']].map(([key,label])=>`<div class="study-note"><small>${label}</small><p>${text(note[key])||'（尚未整理）'}</p></div>`).join('')}</div><form id="studyEditor" hidden>${[['lead','名詞引子'],['own','用自己的話說'],['example','生活中的例子'],['question','還沒想清楚的問題']].map(([key,label])=>`<label>${label}<textarea name="${key}" rows="3">${text(note[key])}</textarea></label>`).join('')}<button type="submit">儲存</button><button type="button" id="studyCancelEdit">取消</button></form></section></div><div class="footnote">整理與文章連結儲存在此瀏覽器。背景：<a href="https://unsplash.com/photos/${config.source}" target="_blank" rel="noreferrer">${config.credit} / Unsplash</a></div>`;
bindManagement();host.querySelectorAll('[data-series]').forEach(b=>b.onclick=()=>{current=Number(b.dataset.series);term=configs[current].terms[0]||'';render()});host.querySelectorAll('[data-term]').forEach(b=>b.onclick=()=>{term=b.dataset.term;render()});
const find=id=>host.querySelector('#'+id);
find('studyAddTerm').onclick=()=>{find('studyTermForm').hidden=false;find('studyTermName').focus()};find('studyCancelTerm').onclick=()=>find('studyTermForm').hidden=true;find('studyTermForm').onsubmit=e=>{e.preventDefault();const name=find('studyTermName').value.trim();if(!name)return;term=name;if(!config.terms.includes(name))config.terms.push(name);data();saveConfigs();render()};
find('studyDeleteTerm').hidden=!term;find('studyDeleteTerm').onclick=()=>{if(!confirm('刪除「'+term+'」名詞及其整理與文章連結？'))return;delete stored[config.key]?.[term];config.terms=config.terms.filter(t=>t!==term);term=config.terms[0]||'';saveConfigs();render()};if(!term){find('studyEdit').disabled=true;find('studyAddArticle').disabled=true;host.querySelector('.study-intro h3').textContent='新增第一個名詞';host.querySelector('.study-intro p').textContent='點選「新增名詞」開始整理這個系列。'}
find('studyEdit').onclick=()=>{find('studyEditor').hidden=false;find('studyRead').hidden=true};find('studyCancelEdit').onclick=()=>{find('studyEditor').hidden=true;find('studyRead').hidden=false};find('studyEditor').onsubmit=e=>{e.preventDefault();for(const key of ['lead','own','example','question'])note[key]=find('studyEditor').elements[key].value.trim();persist();render()};
function showArticles(){const linked=(note.links||[]).map(url=>articlePool.find(a=>a.url===url)).filter(Boolean);const matches=articlePool.filter(a=>tagsForArticle(a).includes(config.tag)&&String(window.ARTICLE_BODIES?.[a.url]||'').includes(term)&&!note.links.includes(a.url));find('studyArticles').innerHTML=(linked.length?'<p class="hint">已連結文章</p>':'')+linked.map(a=>card(a,true)).join('')+(matches.length?'<p class="hint">正文提到此名詞的系列文章</p>'+matches.map(a=>card(a,false)).join(''):'')+(!linked.length&&!matches.length?'<p class="empty">尚未連結文章。可搜尋並加入適合這個名詞的文章。</p>':'');find('studyArticles').querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{note.links=note.links.filter(u=>u!==b.dataset.remove);persist();showArticles()});find('studyArticles').querySelectorAll('[data-link]').forEach(b=>b.onclick=()=>link(b.dataset.link))}
function card(a,linked){const passage=articlePassages(window.ARTICLE_BODIES?.[a.url]).find(p=>p.includes(term));const booksText=namesFor(a.bookRefs)||books.filter(b=>(b.podcastRefs||[]).includes(a.url)).map(b=>b.title).join('、');return `<article class="study-article"><small>${text(a.kind)}${booksText?' · 關聯書籍：'+text(booksText):''}</small><a href="${notionUrl(a.url)}" target="_blank" rel="noreferrer"><h4>${text(a.title)} ↗</h4></a>${passage?`<blockquote>${text(passage)}</blockquote>`:''}<button type="button" ${linked?'data-remove':'data-link'}="${text(a.url)}">${linked?'移除連結':'＋ 加入此名詞'}</button></article>`}
function link(url){if(!note.links.includes(url))note.links.push(url);persist();showArticles();find('studySearchForm').hidden=true}
find('studyAddArticle').onclick=()=>{find('studySearchForm').hidden=false;find('studySearch').focus()};find('studyCancelSearch').onclick=()=>find('studySearchForm').hidden=true;find('studySearchForm').onsubmit=e=>e.preventDefault();find('studySearch').oninput=()=>{const q=find('studySearch').value.trim().toLocaleLowerCase();const results=q?articlePool.filter(a=>[a.title,a.author,...(a.authors||[]),...tagsForArticle(a)].join(' ').toLocaleLowerCase().includes(q)):[];find('studySearchResults').innerHTML=!q?'<p class="hint">輸入關鍵字搜尋文章。</p>':results.length?results.slice(0,20).map(a=>`<button type="button" class="study-result" data-url="${text(a.url)}">${text(a.title)} · ${text(a.kind)}</button>`).join(''):'<p class="hint">沒有符合的文章。</p>';find('studySearchResults').querySelectorAll('[data-url]').forEach(b=>b.onclick=()=>link(b.dataset.url))};showArticles();}
render();
})();
